INFO: Starting training:
        Epochs:          10
        Batch size:      16
        Learning rate:   1e-05
        Training size:   1544
        Validation size: 386
        Checkpoints:     True
        Device:          cuda
        Images scaling:  0.5
        Mixed Precision: False
Epoch 1/10:   0%|                                | 0/1544 [00:42<?, ?img/s]
Traceback (most recent call last):
  File "D:\Uni\Data science lab\rekt\Pytorch-UNet\train.py", line 184, in <module>
    train_net(net=net,
  File "D:\Uni\Data science lab\rekt\Pytorch-UNet\train.py", line 79, in train_net
    for batch in train_loader:
  File "C:\Users\handr\anaconda3\envs\ai\lib\site-packages\torch\utils\data\dataloader.py", line 521, in __next__
    data = self._next_data()
  File "C:\Users\handr\anaconda3\envs\ai\lib\site-packages\torch\utils\data\dataloader.py", line 1203, in _next_data
    return self._process_data(data)
  File "C:\Users\handr\anaconda3\envs\ai\lib\site-packages\torch\utils\data\dataloader.py", line 1229, in _process_data
    data.reraise()
  File "C:\Users\handr\anaconda3\envs\ai\lib\site-packages\torch\_utils.py", line 434, in reraise
    raise exception
AssertionError: Caught AssertionError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "C:\Users\handr\anaconda3\envs\ai\lib\site-packages\torch\utils\data\_utils\worker.py", line 287, in _worker_loop
    data = fetcher.fetch(index)
  File "C:\Users\handr\anaconda3\envs\ai\lib\site-packages\torch\utils\data\_utils\fetch.py", line 49, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "C:\Users\handr\anaconda3\envs\ai\lib\site-packages\torch\utils\data\_utils\fetch.py", line 49, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "C:\Users\handr\anaconda3\envs\ai\lib\site-packages\torch\utils\data\dataset.py", line 363, in __getitem__
    return self.dataset[self.indices[idx]]
  File "D:\Uni\Data science lab\rekt\Pytorch-UNet\utils\data_loading.py", line 61, in __getitem__
    assert len(mask_file) == 1, f'Either no mask or multiple masks found for the ID {name}: {mask_file}'
AssertionError: Either no mask or multiple masks found for the ID 1414: []